spring:
#  mvc:
#      static-path-pattern: /res/**
  web:
    resources:
      static-locations:
        [ classpath:/static/] #      add-mappings: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
